// mksysnum_dragonfly.pl
// NOT MACHINE GENERATED BY THE ABOVE COMMAND; DO EDIT

package syscall

const (

/*
 * System call numbers.
 *
 * DO NOT EDIT-- To regenerate this file, edit syscalls.master followed
 *               by running make sysent in the same directory.
 */

	SYS_syscall	=  0
	SYS_exit	=  1
	SYS_fork	=  2
	SYS_read	=  3
	SYS_write	=  4
	SYS_open	=  5
	SYS_close	=  6
	SYS_wait4	=  7
				/* 8 is old creat */

	SYS_link	=  9
	SYS_unlink	=  10
				/* 11 is obsolete execv */

	SYS_chdir	= 12
	SYS_fchdir	= 13
	SYS_mknod	= 14
	SYS_chmod	= 15
	SYS_chown	= 16
	SYS_break	= 17
	SYS_getfsstat	= 18
				/* 19 is old lseek */

	SYS_getpid	= 20
	SYS_mount	= 21
	SYS_unmount	= 22
	SYS_setuid	= 23
	SYS_getuid	= 24
	SYS_geteuid	= 25
	SYS_ptrace	= 26
	SYS_recvmsg	= 27
	SYS_sendmsg	= 28
	SYS_recvfrom	= 29
	SYS_accept	= 30
	SYS_getpeername	= 31
	SYS_getsockname	= 32
	SYS_access	= 33
	SYS_chflags	= 34
	SYS_fchflags	= 35
	SYS_sync	= 36
	SYS_kill	= 37
				/* 38 is old stat */

	SYS_getppid	= 39
				/* 40 is old lstat */

	SYS_dup	= 41
	SYS_pipe	= 42
	SYS_getegid	= 43
	SYS_profil	= 44
	SYS_ktrace	= 45
				/* 46 is obsolete freebsd3_sigaction */

	SYS_getgid	= 47
				/* 48 is obsolete freebsd3_sigprocmask */

	SYS_getlogin	= 49
	SYS_setlogin	= 50
	SYS_acct	= 51
				/* 52 is obsolete freebsd3_sigpending */

	SYS_sigaltstack	= 53
	SYS_ioctl	= 54
	SYS_reboot	= 55
	SYS_revoke	= 56
	SYS_symlink	= 57
	SYS_readlink	= 58
	SYS_execve	= 59
	SYS_umask	= 60
	SYS_chroot	= 61
				/* 62 is old fstat */
				/* 63 is old getkerninfo */
				/* 64 is old getpagesize */

	SYS_msync	= 65
	SYS_vfork	= 66
				/* 67 is obsolete vread */
				/* 68 is obsolete vwrite */

	SYS_sbrk	= 69
	SYS_sstk	= 70
				/* 71 is old mmap */
				/* 72 is old vadvise */

	SYS_munmap	= 73
	SYS_mprotect	= 74
	SYS_madvise	= 75
				/* 76 is obsolete vhangup */
				/* 77 is obsolete vlimit */
	SYS_mincore	= 78
	SYS_getgroups	= 79
	SYS_setgroups	= 80
	SYS_getpgrp	= 81
	SYS_setpgid	= 82
	SYS_setitimer	= 83
				/* 84 is old wait */
	SYS_swapon	= 85
	SYS_getitimer	= 86
				/* 87 is old gethostname */
				/* 88 is old sethostname */
	SYS_getdtablesize	= 89
	SYS_dup2	= 90
	SYS_fcntl	= 92
	SYS_select	= 93
	SYS_fsync	= 95
	SYS_setpriority	= 96
	SYS_socket	= 97
	SYS_connect	= 98
				/* 99 is old accept */
	SYS_getpriority	= 100
				/* 101 is old send */
				/* 102 is old recv */
				/* 103 is obsolete freebsd3_sigreturn */
	SYS_bind	= 104
	SYS_setsockopt	= 105
	SYS_listen	= 106
				/* 107 is obsolete vtimes */
				/* 108 is old sigvec */
				/* 109 is old sigblock */
				/* 110 is old sigsetmask */
				/* 111 is obsolete freebsd3_sigsuspend */
				/* 112 is old sigstack */
				/* 113 is old recvmsg */
				/* 114 is old sendmsg */
				/* 115 is obsolete vtrace */
	SYS_gettimeofday	= 116
	SYS_getrusage	= 117
	SYS_getsockopt	= 118
	SYS_readv	= 120
	SYS_writev	= 121
	SYS_settimeofday	= 122
	SYS_fchown	= 123
	SYS_fchmod	= 124
				/* 125 is old recvfrom */
	SYS_setreuid	= 126
	SYS_setregid	= 127
	SYS_rename	= 128
				/* 129 is old truncate */
				/* 130 is old ftruncate */
	SYS_flock	= 131
	SYS_mkfifo	= 132
	SYS_sendto	= 133
	SYS_shutdown	= 134
	SYS_socketpair	= 135
	SYS_mkdir	= 136
	SYS_rmdir	= 137
	SYS_utimes	= 138
				/* 139 is obsolete 4.2 sigreturn */
	SYS_adjtime	= 140
				/* 141 is old getpeername */
				/* 142 is old gethostid */
				/* 143 is old sethostid */
				/* 144 is old getrlimit */
				/* 145 is old setrlimit */
				/* 146 is old killpg */
	SYS_setsid	= 147
	SYS_quotactl	= 148
				/* 149 is old quota */
				/* 150 is old getsockname */
	SYS_nfssvc	= 155
				/* 156 is old getdirentries */
	SYS_statfs	= 157
	SYS_fstatfs	= 158
	SYS_getfh	= 161
	SYS_getdomainname	= 162
	SYS_setdomainname	= 163
	SYS_uname	= 164
	SYS_sysarch	= 165
	SYS_rtprio	= 166
	SYS_semsys	= 169
	SYS_msgsys	= 170
	SYS_shmsys	= 171
	SYS_extpread	= 173
	SYS_extpwrite	= 174
	SYS_ntp_adjtime	= 176
	SYS_setgid	= 181
	SYS_setegid	= 182
	SYS_seteuid	= 183
				/* 188 is old stat */
				/* 189 is old fstat */
				/* 190 is old lstat */
	SYS_pathconf	= 191
	SYS_fpathconf	= 192
	SYS_getrlimit	= 194
	SYS_setrlimit	= 195
				/* 196 is old getdirentries */
	SYS_mmap	= 197
	SYS___syscall	= 198
	SYS_lseek	= 199
	SYS_truncate	= 200
	SYS_ftruncate	= 201
	SYS___sysctl	= 202
	SYS_mlock	= 203
	SYS_munlock	= 204
	SYS_undelete	= 205
	SYS_futimes	= 206
	SYS_getpgid	= 207
	SYS_poll	= 209
	SYS___semctl	= 220
	SYS_semget	= 221
	SYS_semop	= 222
	SYS_msgctl	= 224
	SYS_msgget	= 225
	SYS_msgsnd	= 226
	SYS_msgrcv	= 227
	SYS_shmat	= 228
	SYS_shmctl	= 229
	SYS_shmdt	= 230
	SYS_shmget	= 231
	SYS_clock_gettime	= 232
	SYS_clock_settime	= 233
	SYS_clock_getres	= 234
	SYS_nanosleep	= 240
	SYS_minherit	= 250
	SYS_rfork	= 251
	SYS_openbsd_poll	= 252
	SYS_issetugid	= 253
	SYS_lchown	= 254
				/* 272 is old getdents */
	SYS_lchmod	= 274
	SYS_netbsd_lchown	= 275
	SYS_lutimes	= 276
	SYS_netbsd_msync	= 277
				/* 278 is obsolete { */
				/* 279 is obsolete { */
				/* 280 is obsolete { */
	SYS_extpreadv	= 289
	SYS_extpwritev	= 290
	SYS_fhstatfs	= 297
	SYS_fhopen	= 298
				/* 299 is old fhstat */
	SYS_modnext	= 300
	SYS_modstat	= 301
	SYS_modfnext	= 302
	SYS_modfind	= 303
	SYS_kldload	= 304
	SYS_kldunload	= 305
	SYS_kldfind	= 306
	SYS_kldnext	= 307
	SYS_kldstat	= 308
	SYS_kldfirstmod	= 309
	SYS_getsid	= 310
	SYS_setresuid	= 311
	SYS_setresgid	= 312
				/* 313 is obsolete signanosleep */
	SYS_aio_return	= 314
	SYS_aio_suspend	= 315
	SYS_aio_cancel	= 316
	SYS_aio_error	= 317
	SYS_aio_read	= 318
	SYS_aio_write	= 319
	SYS_lio_listio	= 320
	SYS_yield	= 321
	SYS_mlockall	= 324
	SYS_munlockall	= 325
	SYS___getcwd	= 326
	SYS_sched_setparam	= 327
	SYS_sched_getparam	= 328
	SYS_sched_setscheduler	= 329
	SYS_sched_getscheduler	= 330
	SYS_sched_yield	= 331
	SYS_sched_get_priority_max	= 332
	SYS_sched_get_priority_min	= 333
	SYS_sched_rr_get_interval	= 334
	SYS_utrace	= 335
				/* 336 is obsolete freebsd4_sendfile */
	SYS_kldsym	= 337
	SYS_jail	= 338
	SYS_sigprocmask	= 340
	SYS_sigsuspend	= 341
	SYS_sigaction	= 342
	SYS_sigpending	= 343
	SYS_sigreturn	= 344
	SYS_sigtimedwait	= 345
	SYS_sigwaitinfo	= 346
	SYS___acl_get_file	= 347
	SYS___acl_set_file	= 348
	SYS___acl_get_fd	= 349
	SYS___acl_set_fd	= 350
	SYS___acl_delete_file	= 351
	SYS___acl_delete_fd	= 352
	SYS___acl_aclcheck_file	= 353
	SYS___acl_aclcheck_fd	= 354
	SYS_extattrctl	= 355
	SYS_extattr_set_file	= 356
	SYS_extattr_get_file	= 357
	SYS_extattr_delete_file	= 358
	SYS_aio_waitcomplete	= 359
	SYS_getresuid	= 360
	SYS_getresgid	= 361
	SYS_kqueue	= 362
	SYS_kevent	= 363
	SYS_sctp_peeloff	= 364
	SYS_lchflags	= 391
	SYS_uuidgen	= 392
	SYS_sendfile	= 393
	SYS_varsym_set	= 450
	SYS_varsym_get	= 451
	SYS_varsym_list	= 452
				/* 453 is obsolete upc_register */
				/* 454 is obsolete upc_control */
				/* 455 is obsolete caps_sys_service */
				/* 456 is obsolete caps_sys_client */
				/* 457 is obsolete caps_sys_close */
				/* 458 is obsolete caps_sys_put */
				/* 459 is obsolete caps_sys_reply */
				/* 460 is obsolete caps_sys_get */
				/* 461 is obsolete caps_sys_wait */
				/* 462 is obsolete caps_sys_abort */
				/* 463 is obsolete caps_sys_getgen */
				/* 464 is obsolete caps_sys_setgen */
	SYS_exec_sys_register	= 465
	SYS_exec_sys_unregister	= 466
	SYS_sys_checkpoint	= 467
	SYS_mountctl	= 468
	SYS_umtx_sleep	= 469
	SYS_umtx_wakeup	= 470
	SYS_jail_attach	= 471
	SYS_set_tls_area	= 472
	SYS_get_tls_area	= 473
	SYS_closefrom	= 474
	SYS_stat	= 475
	SYS_fstat	= 476
	SYS_lstat	= 477
	SYS_fhstat	= 478
	SYS_getdirentries	= 479
	SYS_getdents	= 480
	SYS_usched_set	= 481
	SYS_extaccept	= 482
	SYS_extconnect	= 483
				/* 484 is obsolete syslink */
	SYS_mcontrol	= 485
	SYS_vmspace_create	= 486
	SYS_vmspace_destroy	= 487
	SYS_vmspace_ctl	= 488
	SYS_vmspace_mmap	= 489
	SYS_vmspace_munmap	= 490
	SYS_vmspace_mcontrol	= 491
	SYS_vmspace_pread	= 492
	SYS_vmspace_pwrite	= 493
	SYS_extexit	= 494
	SYS_lwp_create	= 495
	SYS_lwp_gettid	= 496
	SYS_lwp_kill	= 497
	SYS_lwp_rtprio	= 498
	SYS_pselect	= 499
	SYS_statvfs	= 500
	SYS_fstatvfs	= 501
	SYS_fhstatvfs	= 502
	SYS_getvfsstat	= 503
	SYS_openat	= 504
	SYS_fstatat	= 505
	SYS_fchmodat	= 506
	SYS_fchownat	= 507
	SYS_unlinkat	= 508
	SYS_faccessat	= 509
	SYS_mq_open	= 510
	SYS_mq_close	= 511
	SYS_mq_unlink	= 512
	SYS_mq_getattr	= 513
	SYS_mq_setattr	= 514
	SYS_mq_notify	= 515
	SYS_mq_send	= 516
	SYS_mq_receive	= 517
	SYS_mq_timedsend	= 518
	SYS_mq_timedreceive	= 519
	SYS_ioprio_set	= 520
	SYS_ioprio_get	= 521
	SYS_chroot_kernel	= 522
	SYS_renameat	= 523
	SYS_mkdirat	= 524
	SYS_mkfifoat	= 525
	SYS_mknodat	= 526
	SYS_readlinkat	= 527
	SYS_symlinkat	= 528
	SYS_swapoff	= 529
	SYS_vquotactl	= 530
	SYS_linkat	= 531
	SYS_eaccess	= 532
	SYS_lpathconf	= 533
	SYS_MAXSYSCALL	= 534
)
